version: '3.7'

services:

  kafka:
    image: bitnami/kafka:latest
    environment:
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@localhost:9093
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
    ports:
      - "9092:9092"
    restart: unless-stopped

  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: jitsu
      POSTGRES_PASSWORD: jitsu
      POSTGRES_DB: jitsu
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:6
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redisdata:/data
    restart: unless-stopped

  bulker:
    image: jitsucom/bulker:latest
    environment:
      - BULKER_MODE=server
      - BULKER_REDIS_URL=redis://redis:6379
      - BULKER_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - BULKER_LOG_LEVEL=info
      - BULKER_BATCH_SIZE=1000
      - BULKER_FLUSH_INTERVAL_SEC=2
      - BULKER_MAX_PARALLEL_REQUESTS=10
    ports:
      - "3042:3042"
    depends_on:
      - kafka
      - redis
    restart: unless-stopped

  jitsu:
    image: jitsucom/jitsu:latest
    environment:
      - REDIS_URL=redis://redis:6379
      - CONFIGURATOR_META_STORAGE=postgres
      - CONFIGURATOR_META_DSN=postgres://jitsu:jitsu@postgres:5432/jitsu?sslmode=disable
      - EVENTNATIVE_META_STORAGE=postgres
      - EVENTNATIVE_META_DSN=postgres://jitsu:jitsu@postgres:5432/jitsu?sslmode=disable
      - EVENTNATIVE_BULKER_URL=http://bulker:3042
      - DESTINATIONS_BATCH_SIZE=1000
      - DESTINATIONS_BATCH_TIMEOUT_SEC=2
      - WORKERS=4
      - BULKER_WORKERS=4
    expose:
      - "8000"
    depends_on:
      - postgres
      - redis
      - bulker
    restart: unless-stopped

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - jitsu
    restart: unless-stopped

volumes:
  pgdata:
  redisdata:
